# Generated by Django 3.2.11 on 2022-01-18 12:27

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionModel',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('criterion_id', models.AutoField(help_text='Unique ID for criterion', primary_key=True, serialize=False, verbose_name='Criterion ID')),
                ('criterion_name', models.CharField(help_text='Name of Criterion', max_length=100, verbose_name='Criterion Name')),
            ],
            options={
                'verbose_name': 'Criteria',
                'verbose_name_plural': 'Criterion',
                'db_table': 'criteria',
                'ordering': ('criterion_name',),
            },
        ),
    ]
