# Generated by Django 3.2.11 on 2022-01-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='category_alias',
            field=models.CharField(default='', help_text='Category Alias', max_length=50, verbose_name='Category Alias'),
        ),
    ]
