# Generated by Django 3.2.11 on 2022-01-18 12:27

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('region_id', models.AutoField(help_text='Unique ID for region', primary_key=True, serialize=False, verbose_name='Region ID')),
                ('region_name', models.CharField(help_text='Name of Region', max_length=100, verbose_name='Region Name')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'regions',
                'ordering': ('created',),
            },
        ),
    ]
