# Generated by Django 3.2.11 on 2022-01-21 06:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyStatisticsModel',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('statistics_id', models.AutoField(help_text='Unique ID for statistics', primary_key=True, serialize=False, verbose_name='Statistic ID')),
                ('year', models.IntegerField(help_text='Year for statistics', verbose_name='Year')),
                ('highlight_stats', models.FloatField(help_text='Statistics', verbose_name='Statistics')),
                ('category', models.ForeignKey(help_text='Category', on_delete=django.db.models.deletion.PROTECT, to='categories.categorymodel', verbose_name='Category')),
                ('region', models.ForeignKey(help_text='Region', on_delete=django.db.models.deletion.PROTECT, to='regions.regionmodel', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Previous Year Statistic',
                'verbose_name_plural': 'Previous Year Statistics',
                'db_table': 'prev_year_statistics',
                'ordering': ('year', 'region', 'category'),
            },
        ),
    ]
