# Generated by Django 3.2.11 on 2022-01-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prev_year_highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlystatisticsmodel',
            name='highlight_stats',
            field=models.FloatField(default=-1, help_text='Statistics', verbose_name='Statistics'),
        ),
    ]
